"""test running migrations

Revision ID: 05409dbac3c7
Revises: 280654fb2881
Create Date: 2024-07-09 13:31:31.134058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05409dbac3c7'
down_revision = '280654fb2881'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
