"""test running migrations

Revision ID: 1e5934bc1a0a
Revises: b1c4fec6ca92
Create Date: 2024-07-09 13:39:03.252648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e5934bc1a0a'
down_revision = 'b1c4fec6ca92'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
