"""test running migrations

Revision ID: 280654fb2881
Revises: 37fd4ba9080f
Create Date: 2024-07-09 13:29:52.626195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '280654fb2881'
down_revision = '37fd4ba9080f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
