"""test running migrations

Revision ID: 33172c61217d
Revises: 7910d8825f1d
Create Date: 2024-07-09 13:36:22.684776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33172c61217d'
down_revision = '7910d8825f1d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
