"""test running migrations

Revision ID: 6b6b6b5c12c9
Revises: 651e25e0ea83
Create Date: 2024-07-10 10:44:30.426911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b6b6b5c12c9'
down_revision = '651e25e0ea83'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
