"""test running migrations

Revision ID: 7910d8825f1d
Revises: 05409dbac3c7
Create Date: 2024-07-09 13:33:38.202856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7910d8825f1d'
down_revision = '05409dbac3c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
