"""test running migrations

Revision ID: b1c4fec6ca92
Revises: 33172c61217d
Create Date: 2024-07-09 13:38:50.858422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1c4fec6ca92'
down_revision = '33172c61217d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
