"""test running migrations

Revision ID: be27d1d45638
Revises: 1e5934bc1a0a
Create Date: 2024-07-09 15:36:33.935300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be27d1d45638'
down_revision = '1e5934bc1a0a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
